version: '3.8'
services:
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_DB: bran_db
      POSTGRES_USER: bran_user
      POSTGRES_PASSWORD: secure_password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

