apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: bran-hpa
  namespace: fampay
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bran
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hodor-hpa
  namespace: fampay
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hodor
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
